apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
##3specification about the deployment 
spec:
  replicas: 2 #going to create two pod 
  selector: #the purpose of .spec.selector: define how the replicaset is going to find which pod to manage . 
    matchLabels: #the same label i have put using match label expression
      app: nginx
  ###inside the pod we need to deploy our container image. 
  template:
    metadata:
      labels:
       app: nginx 
    spec:
      containers:
      - name: nginx-app 
        image: ramakrishna8254/week:v2
        ports:
        - containerPort: 8080
