apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-04-26T12:26:06Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: nginx
    app.kubernetes.io/instance: dev
  name: nginx-service
  namespace: default
  resourceVersion: "518471"
  uid: 2ed0f89b-1a42-4df6-87c9-73e8c7aa6418
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.20.137.102
  clusterIPs:
  - 172.20.137.102
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30579
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: a2ed0f89b1a424df687c973e8c7aa641-1808946614.ap-southeast-1.elb.amazonaws.com
