apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-03-14T14:39:06Z"
  labels:
    app: nginx
  name: nginx-service
  namespace: default
  resourceVersion: "44148"
  uid: 4785c9ac-76e8-4db1-854a-080d3670db5b
spec:
  clusterIP: 10.103.248.203
  clusterIPs:
  - 10.103.248.203
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30119
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
