apiVersion: v1
kind: Service
metadata:  
  labels:
    app: nginx
    app.kubernetes.io/instance: dev
  name: nginx-service
  namespace: default  
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.20.137.102
  clusterIPs:
  - 172.20.137.102
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30579
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: a2ed0f89b1a424df687c973e8c7aa641-1808946614.ap-southeast-1.elb.amazonaws.com
